// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire_demo

import (
	"backend/test/demo/wire_demo/repository"
	"backend/test/demo/wire_demo/repository/dao"
)

// Injectors from wire.go:

func InitRepo() *repository.UserRepository {
	db := InitDb()
	userDao := dao.NewUserDao(db)
	userRepository := repository.NewUserRepository(userDao)
	return userRepository
}
