// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-web/internal/ioc"
	"gin-web/internal/repository"
	"gin-web/internal/repository/cache"
	"gin-web/internal/repository/dao"
	"gin-web/internal/service"
	"gin-web/internal/web"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	db := ioc.InitDB()
	iUserDao := dao.NewUserDAO(db)
	iUserRepository := repository.NewUserRepository(iUserDao)
	iUserService := service.NewUserService(iUserRepository)
	cmdable := ioc.InitRedis()
	ismsService := ioc.InitSmsService(cmdable)
	iCodeCache := cache.NewCodeCache(cmdable)
	iCodeRepo := repository.NewCodeRepository(iCodeCache)
	iCodeService := service.NewCodeService(ismsService, iCodeRepo)
	userHandler := web.NewUserHandler(iUserService, iCodeService)
	iCaptcha := service.NewCaptchaService()
	captchaHandler := web.NewCaptchaHandler(iCaptcha)
	iEnterpriseDao := dao.NewEnterpriseDao(db)
	companyCache := cache.NewRedisCompanyCache(cmdable)
	iCompany := repository.NewCompanyRepo(iEnterpriseDao, companyCache)
	iExcelParseService := service.NewExcelParserService(iCompany)
	excelHandler := web.NewExcelHandler(iExcelParseService)
	v := ioc.InitMiddlewares(cmdable)
	engine := ioc.InitGin(userHandler, captchaHandler, excelHandler, v)
	return engine
}
